// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storage.Data;

namespace Storage.Migrations
{
    [DbContext(typeof(StorageContext))]
    partial class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Storage.Models.Entites.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mobile",
                            Count = 156,
                            Description = "Beskrivning av telefonen här",
                            Name = "Iphone 12",
                            OrderDate = new DateTime(2021, 8, 10, 14, 25, 22, 905, DateTimeKind.Local).AddTicks(5154),
                            Price = 15600,
                            Shelf = "4B"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mobile",
                            Count = 98,
                            Description = "Beskrivning av telefonen här",
                            Name = "S20",
                            OrderDate = new DateTime(2021, 7, 24, 14, 25, 22, 908, DateTimeKind.Local).AddTicks(591),
                            Price = 12450,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computers",
                            Count = 23,
                            Description = "Beskrivning här",
                            Name = "MacBook",
                            OrderDate = new DateTime(2021, 8, 11, 14, 25, 22, 908, DateTimeKind.Local).AddTicks(635),
                            Price = 45600,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Computer",
                            Count = 32,
                            Description = "Beskrivning här",
                            Name = "Suface X",
                            OrderDate = new DateTime(2021, 7, 7, 14, 25, 22, 908, DateTimeKind.Local).AddTicks(639),
                            Price = 26850,
                            Shelf = "5C"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Office Supplies",
                            Count = 15651,
                            Description = "Beskrivning här",
                            Name = "Pen",
                            OrderDate = new DateTime(2021, 8, 10, 14, 25, 22, 908, DateTimeKind.Local).AddTicks(642),
                            Price = 1,
                            Shelf = "45W"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
